### ISSUE TITLE
With Spring boot 2.2.6.RELEASE, not working

### ISSUE THREAD

**Issue by soumencemk** [kwon37xi/hibernate5-memcached#4]
## With Spring boot 2.2.6.RELEASE, that comes with Hibernate 5.4, following error is happening - 
```
Caused by: org.hibernate.boot.registry.selector.spi.StrategySelectionException: Unable to resolve name [kr.pe.kwonnam.hibernate5memcached.Hibernate5MemcachedRegionFactory] as strategy [org.hibernate.cache.spi.RegionFactory]
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.selectStrategyImplementor(StrategySelectorImpl.java:133)
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveStrategy(StrategySelectorImpl.java:212)
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.resolveStrategy(StrategySelectorImpl.java:169)
        at org.hibernate.cache.internal.RegionFactoryInitiator.resolveRegionFactory(RegionFactoryInitiator.java:93)
        at org.hibernate.cache.internal.RegionFactoryInitiator.initiateService(RegionFactoryInitiator.java:47)
        at org.hibernate.cache.internal.RegionFactoryInitiator.initiateService(RegionFactoryInitiator.java:32)
        at org.hibernate.boot.registry.internal.StandardServiceRegistryImpl.initiateService(StandardServiceRegistryImpl.java:101)
        at org.hibernate.service.internal.AbstractServiceRegistryImpl.createService(AbstractServiceRegistryImpl.java:263)
        ... 131 common frames omitted
Caused by: org.hibernate.boot.registry.classloading.spi.ClassLoadingException: Unable to load class [kr.pe.kwonnam.hibernate5memcached.Hibernate5MemcachedRegionFactory]
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:136)
        at org.hibernate.boot.registry.selector.internal.StrategySelectorImpl.selectStrategyImplementor(StrategySelectorImpl.java:129)
        ... 138 common frames omitted
Caused by: java.lang.NoClassDefFoundError: org/hibernate/cache/spi/EntityRegion
        at java.lang.Class.forName0(Native Method)
        at java.lang.Class.forName(Class.java:348)
        at org.hibernate.boot.registry.classloading.internal.ClassLoaderServiceImpl.classForName(ClassLoaderServiceImpl.java:130)
        ... 139 common frames omitted
Caused by: java.lang.ClassNotFoundException: org.hibernate.cache.spi.EntityRegion
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1365)
        at org.apache.catalina.loader.WebappClassLoaderBase.loadClass(WebappClassLoaderBase.java:1188)
        ... 142 common frames omitted
```

**Comment by kwonnamsonwwh** [comment]
Please do not use this project.
refer to https://github.com/mihaicostin/hibernate-l2-memcached or others.

**Comment by kwon37xi** [comment]
Please do not use this project.
refer to https://github.com/mihaicostin/hibernate-l2-memcached or others.
